name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Generate Flutter Platform Files
        run: flutter create . --project-name ayesha_candidate_management --org com.ayesha --platforms android

      - name: Fix Android Namespace for old plugins
        run: |
          cat <<EOF >> android/build.gradle
          subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty("android")) {
                      project.android {
                          if (namespace == null) {
                              namespace project.group
                          }
                      }
                  }
              }
          }
          EOF

      - name: Overwrite with Custom Source
        run: cp -r src/* lib/

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ayesha-Candidate-Management-APK
          path: build/app/outputs/flutter-apk/app-release.apk
